version: '3'

services:
  backend:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: fivepointslab/academy-platform/academy-platform-backend:latest
    container_name: backend
    restart: unless-stopped
    environment:
      - dbhost="158.177.32.40" 
    ports:
      - "3000:3000"