version: '3'

services:
  backend:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: backend
    container_name: backend
    restart: unless-stopped
    environment:
      - dbhost=db 
    ports:
      - "3000:3000"
  db:
    image: mvertes/alpine-mongo
    container_name: db
    restart: unless-stopped