---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: academy-backend-prod-__CI_ENVIRONMENT_SLUG__
  namespace: academy-backend
  labels:
    app: academy-backend-prod-__CI_ENVIRONMENT_SLUG__
    ref: prod
    track: stable
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
    app.gitlab.com/env: __CI_ENVIRONMENT_SLUG__
    app.gitlab.com/app: academy-backend-prod-__CI_ENVIRONMENT_SLUG__

spec:
  replicas: 2
  selector:
    matchLabels:
      app: academy-backend-prod-__CI_ENVIRONMENT_SLUG__
      ref: prod
  template:
    metadata:
      labels:
        app: academy-backend-prod-__CI_ENVIRONMENT_SLUG__
        ref: prod
        track: stable
    spec:
      containers:
        - name: app
          image: __CI_REGISTRY_IMAGE__:__VERSION__
          volumeMounts:
          - mountPath: "/app/ssl"
            name: mongo-ssl
            readOnly: true
          env:
          - name: dbhost
            value: "admin:FivePoints2020@5955fc2a-3bf5-4e0e-b684-ddb6ebe7bfd4-0.br38q28f0334iom5lv4g.databases.appdomain.cloud:30898,5955fc2a-3bf5-4e0e-b684-ddb6ebe7bfd4-1.br38q28f0334iom5lv4g.databases.appdomain.cloud"
          - name: redishost
            value: "redis"
          imagePullPolicy: Always
          ports:
          - name: http-metrics
            protocol: TCP
            containerPort: 80
      volumes:
        - name: mongo-ssl
          secret:
            secretName: mongo-ssl
          restartPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 128Mi

          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8000
          #   initialDelaySeconds: 3
          #   timeoutSeconds: 2
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8000
          #   initialDelaySeconds: 3
          #   timeoutSeconds: 2
